### ISSUE TITLE
xdl最新版本在x86的架构下，运行在模拟器上会crash

### ISSUE THREAD

**Issue by zqhGeek** [hexhacking/xDL#10]
### xDL Version

1.2.1

### Android OS Version

9

### Android ABIs

x86

### Device Manufacturers and Models

模拟器

### Describe the Bug

![image](https://user-images.githubusercontent.com/11883200/222088910-958c4c5c-0de6-4fff-b8cf-0872e15e7a3d.png)

必现，使用的是mumu模拟器，夜神模拟器也会闪退，会卡死或者无响应

**Comment by zqhGeek** [comment]
在1.1.2版本上是正常的

**Comment by caikelun** [comment]
确实有问题，感谢反馈。
应该是新版本加了 LLVM machine outliner 编译优化引入的问题，我们尽快修复后发个新版本。

**Comment by caikelun** [comment]
@zqhGeek 我们在新发布的 xDL 2.0.0 中修复了这个问题，有空的话请更新验证一下，谢谢
https://github.com/hexhacking/xDL/releases/tag/v2.0.0

**Comment by TheMercen133** [comment]
"Crash when using xdl_sym on x86" to call libc function symbol with xdl_sym, if I use dlsym directly from libc it doesn't cause a crash.

Looks like this problem is not solved yet, I use a different emulator and a different android version on x86 it still crashes, other than that it runs fine
