### ISSUE TITLE
Android9.0-Android6.0 arm64模式下获取libart.so加载基地址是有问题的

### ISSUE THREAD

**Issue by LivedForward** [hexhacking/xDL#11]
### xDL Version

1.1.3

### Android OS Version

8.1.0

### Android ABIs

arm64-v8a

### Device Manufacturers and Models

小米平板4

### Describe the Bug

![2023-03-02_140458](https://user-images.githubusercontent.com/19593304/222345292-add1a738-db1f-4feb-9818-7bf033f5a4d6.png)

![2023-03-02_135959](https://user-images.githubusercontent.com/19593304/222345360-51c11de6-7fd7-468b-a023-804ff7b861ad.png)

![2023-03-02_140009](https://user-images.githubusercontent.com/19593304/222345375-abc25104-702a-41fe-91c6-7213a66f0e40.png)

void *so_base_addr = xdlInfo.dli_fbase;
so_base_addr 输出就是soStartAddrFromMaps这项的地址为0x799cbdb000，但是我自己手动扫描maps时，发现libart.so的加载地址，也就是第一项，为0x799cc00000。目前只发现在 Android9.0-Android6.0 arm64/32模式下libart.so会出现此情况。libc.so都是正确的，没有任何问题。（自身做了mmap操作，但是都在调用xdl之前munmap了或者在xdl调用之后mmap）

**Comment by caikelun** [comment]
`xdl_info()` 获取的 `dli_fbase` 是 so 的 `load_bias`，你说的 `0x799cc00000` 是 `load_start` 或者叫 `load_base`。这两者并不总是相等的。

另外，系统 `dladdr()` 获取的 `dli_fbase` 也是 so 的 `load_bias`。

可以参考下linker：https://cs.android.com/android/platform/superproject/+/master:bionic/linker/linker_phdr.cpp;l=119;bpv=0;bpt=1

**Comment by XMDS** [comment]
@caikelun  是否能够提供获取库的load_base和在内存中长度的API？

**Comment by caikelun** [comment]
目前不会提供。`load_base` 在正常的 DL 系列函数中都是不返回的，因为仅从 DL 系列函数的角度出发 `load_base` 没有用处。

你如果直接源码集成 xDL 的话，可以把 `xdl_open()` 返回的 `void *` 转成 `xdl_t *` 类型，然后直接读这里的 `base` 变量，就是 `load_base`:
https://github.com/hexhacking/xDL/blob/master/xdl/src/main/cpp/xdl.c#L105

**Comment by caikelun** [comment]
目前不会提供。`load_base` 在正常的 DL 系列函数中都是不返回的，因为仅从 DL 系列函数的角度出发 `load_base` 没有用处。

你如果直接源码集成 xDL 的话，可以把 `xdl_open()` 返回的 `void *` 转成 `xdl_t *` 类型，然后直接读这里的 `base` 变量，就是 `load_base`:
https://github.com/hexhacking/xDL/blob/master/xdl/src/main/cpp/xdl.c#L105

**Comment by LivedForward** [comment]
**我只能说太多谢大佬了。**

**Comment by caikelun** [comment]
还有一种方法是通过 `xdl_iterate_phdr()` 遍历到你要找的 so 库，其中的 `dlpi_addr` 就是 `load_bias`，然后通过 `dlpi_phdr` 遍历 program headers，再自己计算一下 `load_base`，具体可以参考下 xDL 的写法：

**Comment by XMDS** [comment]
```c++
uintptr_t GetLibBase(const char* libName, pid_t pid)
    {
        uintptr_t address = 0;
        char buffer[2048] = { 0 }, fname[2048] = { 0 };
        if (pid < 0)
            strcpy(fname, "/proc/self/maps");
        else
            snprintf(fname, sizeof(fname), "/proc/%d/maps", pid);
        FILE* fp = fopen(fname, "rt");
        if (fp != NULL)
        {
            while (fgets(buffer, sizeof(buffer) - 1, fp))
            {
                if (strstr(buffer, libName))
                {
                    address = (uintptr_t)strtoul(buffer, NULL, 16);
                    break;
                }
            }
            fclose(fp);
        }
        return address;
    }
```
感谢，但目前我们使用这样的代码来获取load base。

**Comment by XMDS** [comment]
> 目前不会提供。`load_base` 在正常的 DL 系列函数中都是不返回的，因为仅从 DL 系列函数的角度出发 `load_base` 没有用处。
> 
> 你如果直接源码集成 xDL 的话，可以把 `xdl_open()` 返回的 `void *` 转成 `xdl_t *` 类型，然后直接读这里的 `base` 变量，就是 `load_base`: https://github.com/hexhacking/xDL/blob/master/xdl/src/main/cpp/xdl.c#L105

也许您可以将它作为xdl_info和xdl_addr的添加额外信息？事实上，load_bass在某些情况是经常被使用。也许您不知道，您的项目在手游（例如UE\U3D引擎）的功能插件、作弊插件等被经常使用，很多手游hook/dump库都使用了xdl

**Comment by caikelun** [comment]
这个问题的详细解释请参考这里：https://github.com/hexhacking/xDL/pull/12
感谢各位的关注。
