### ISSUE TITLE
在雷电模拟器中获取动态库libart.so  地址失败

### ISSUE THREAD

**Issue by jinghaifeng1** [hexhacking/xDL#16]
### xDL Version

2.0.0

### Android OS Version

9.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

雷电模拟器 9.0.35   android 9.0(64位)

### Describe the Bug

我打了一个包含32位和64位动态库的apk，安装到雷电模拟器后，尝试 
xdl_open(“libart.so”,  XDL_DEFAULT);
结果返回了nullptr
需要特别说明的是，雷电模拟器运行的是32的动态库（实际我提供了64位的库，并且模拟器自身也是64位的）
![image](https://github.com/hexhacking/xDL/assets/20569882/a5f1315c-8f48-4ab8-9a40-291bb454889c)

![image](https://github.com/hexhacking/xDL/assets/20569882/e2aac0d5-f074-4412-9b1b-6b86648fed19)

同样的代码，我在真机上尝试过，是可以正常获取到目标地址的

**Comment by 2361788963** [comment]
我也遇到了这个问题，可以试试Dobby的DobbySymbolResolver能正常获取

**Comment by caikelun** [comment]
xDL 目前不支持模拟器，因为我工作中目前不涉及到模拟器，没有时间精力去适配调试。如果有兴趣，欢迎PR。
