### ISSUE TITLE
Can't use vendor namespace libraries

### ISSUE THREAD

**Issue by MDNSSKNGHT** [hexhacking/xDL#20]
### xDL Version

2.1.1

### Android OS Version

14

### Android ABIs

armeabi-v7a, arm64-v8a

### Device Manufacturers and Models

Samsung Galaxy A53 5G

### Describe the Bug

xdl_open returns null if I try to open any library in the vendor namespace. Attaching log from sample app.
```
xdl_tag                 com.mdnssknght.mycamera              I  +++ xdl_open + xdl_info + xdl_dsym + xdl_addr
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_open(libart.so) : handle b4000071f32906d0
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_info(b4000071f32906d0) : 71afc12000 /apex/com.android.art/lib64/libart.so (phdr 71afc12040, phnum 10)
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_dsym(_ZN3artL16FindOatMethodForEPNS_9ArtMethodENS_11PointerSizeEPb) : addr 71afefb4cc, sz 3400
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_addr(71afefb4cc) : 71afc12000 /apex/com.android.art/lib64/libart.so (phdr 71afc12040, phnum 10), 71afefb4cc _ZN3artL16FindOatMethodForEPNS_9ArtMethodENS_11PointerSizeEPb.__uniq.231987612005477677052516648077052451092.llvm.3250098303042339366 (sz 3400)
...
xdl_tag                 com.mdnssknght.mycamera              I  --- dlopen(libOpenCL.so) : handle 0
xdl_tag                 com.mdnssknght.mycamera              I  +++ xdl_open + xdl_info + xdl_sym + xdl_addr
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_open(libOpenCL.so) : handle 0
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_info(0) : 0 (NULL) (phdr 0, phnum 0)
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_sym(clCreateContext) : addr 0, sz 0
xdl_tag                 com.mdnssknght.mycamera              I  >>> xdl_addr(0) : FAILED
```

**Comment by MDNSSKNGHT** [comment]
I have not tried but if I try to request root permissions will it fix this problem?

**Comment by caikelun** [comment]
The sample APP is just an example of calling the API. The specific use still needs to be adapted according to the Android OS version and model.

On Samsung Galaxy A53 5G (Android 14), `/vendor/lib64/libOpenCL.so` is a soft link pointing to `/vendor/lib64/egl/libGLES_mali.so`. So what is saved in the `solist` of the `linker` is `libGLES_mali.so`.

You can change
```C
#define BASENAME_LIBOPENCL   "libOpenCL.so"
```
 to
```C
#define BASENAME_LIBOPENCL   "libGLES_mali.so"
```
and try again.

Good luck.

**Comment by MDNSSKNGHT** [comment]
Thanks for replying, actually my goal wasn't to load libOpenCL.so but another vendor library which is libexynoscamera3.so and the problem is that I can't load it, it ends up with a "not found" error.

**Comment by MDNSSKNGHT** [comment]
I tried to put a custom library to vendor/lib and vendor/lib64 and load it but again it says lib not found (even after some sepolicy patches)

**Comment by caikelun** [comment]
> Thanks for replying, actually my goal wasn't to load libOpenCL.so but another vendor library which is libexynoscamera3.so and the problem is that I can't load it, it ends up with a "not found" error.

Okay, let's look into it......

```shell
a53x:/ $ ls -alZ /vendor/lib64/egl/libGLES_mali.so
-rw-r--r-- 1 root root u:object_r:same_process_hal_file:s0  40434040 2021-01-01 08:00 /vendor/lib64/egl/libGLES_mali.so

a53x:/ $ ls -alZ /vendor/lib64/libexynoscamera3.so                                                                                    
-rw-r--r-- 1 root root u:object_r:vendor_file:s0  3430400 2021-01-01 08:00 /vendor/lib64/libexynoscamera3.so
```

As you can see, `libexynoscamera3.so`'s security context is `vendor_file`, which mean it can be accessed only in non-coredomain. So it cannot be accessed in the app process because it is protected by SELinux. You can try again after turning off SELinux on the rooted device.

`xdl_open` is powerless against such SELinux-protected libraries.

https://source.android.com/docs/core/permissions/namespaces_libraries#adding-additional-native-libraries
https://source.android.com/docs/core/architecture/vndk/dir-rules-sepolicy#sphal

**Comment by MDNSSKNGHT** [comment]
Indeed I was able to load the library after disabling SELinux, I tried to use shadowhook to it but it didn't work although I believe it is out of the scope of this issue, much appreciated.
