### ISSUE TITLE
关于批量hook和xdl_iterate_phdr

### ISSUE THREAD

**Issue by XMDS** [hexhacking/xDL#24]
老师你好，我正在Inlinehook多个so中相同的符号(函数)，我使用xdl_iterate_phdr遍历当前加载的so，并进行过滤，在回调函数中，拿到lib_name后，我需要获取handle才能查找符号地址。这里有个问题是，不管我调用xdl_open还是dlopen似乎都会导致crash。因为xdl_open内部也会调用xdl_iterate_phdr来遍历库比较，这导致xdl_iterate_phdr似乎重入了，由于xdl_iterate_phdr最终调用的是安卓的dl_iterate_phdr函数，而这些dl函数内部有mutex锁，会导致死锁，我无法实现我想做的事情。
也许可以通过xdl_open拿handle的方法(在xdl_iterate_phdr的回调函数里做同样的事情):
```c++
// found the target ELF
  if (NULL == ((*self) = calloc(1, sizeof(xdl_t)))) return 1;  // return failed
  if (NULL == ((*self)->pathname = strdup((const char *)info->dlpi_name))) {
    free(*self);
    *self = NULL;
    return 1;  // return failed
  }
  (*self)->load_bias = info->dlpi_addr;
  (*self)->dlpi_phdr = info->dlpi_phdr;
  (*self)->dlpi_phnum = info->dlpi_phnum;
  (*self)->dynsym_try_load = false;
  (*self)->symtab_try_load = false;
  return 1;  // return OK
```
这里可以在自己的回调函数里同样的实现，创建一个xdl_t对象，info信息传给xdl_t对象，把对象地址传给xdl_sym应该也行

或者还有其他方式吗？如果xdl_iterate_phdr也能传递xdl handle到回调函数就好了

**Comment by caikelun** [comment]
你好，

从性能角度出发，你的需求应该加一个函数：`void *xdl_open2(struct dl_phdr_info *info)` ，通过 `xdl_iterate_phdr` 返回的系统 `struct dl_phdr_info` 类型来创建 xdl handle。逻辑大概就是你写的这些，我觉得应该没啥问题。如果需要这样的 API 我可以加一个，你也可以自己改改先用着。

如果不考虑性能，也可以把 `xdl_iterate_phdr` 遍历时获取到的 `struct dl_phdr_info` 都先在内存中保存下来，等 `xdl_iterate_phdr` 返回后，再去逐个调用 `xdl_open`。这样性能肯定比较差。

**Comment by XMDS** [comment]
> 你好，
> 
> 从性能角度出发，你的需求应该加一个函数：`void *xdl_open2(struct dl_phdr_info *info)` ，通过 `xdl_iterate_phdr` 返回的系统 `struct dl_phdr_info` 类型来创建 xdl handle。逻辑大概就是你写的这些，我觉得应该没啥问题。如果需要这样的 API 我可以加一个，你也可以自己改改先用着。
> 
> 如果不考虑性能，也可以把 `xdl_iterate_phdr` 遍历时获取到的 `struct dl_phdr_info` 都先在内存中保存下来，等 `xdl_iterate_phdr` 返回后，再去逐个调用 `xdl_open`。这样性能肯定比较差。

我已经添加了，它很好的运行。xdl添加会更好，我建议还需一个通过xdl_info_t获取handle(xdl_t)的API

**Comment by caikelun** [comment]
我先增加了 `void *xdl_open2(struct dl_phdr_info *info)`：  https://github.com/hexhacking/xDL/commit/7c2324624bdd9fac8bc642368d580081d11de004

“通过xdl_info_t获取handle(xdl_t)”有比较合理的使用场景吗？如果没有的话我还是暂时不想增加更多的public API了。

**Comment by XMDS** [comment]
> 我先增加了 `void *xdl_open2(struct dl_phdr_info *info)`：  https://github.com/hexhacking/xDL/commit/7c2324624bdd9fac8bc642368d580081d11de004
> 
> “通过xdl_info_t获取handle(xdl_t)”有比较合理的使用场景吗？如果没有的话我还是暂时不想增加更多的public API了。

似乎用处不大，现在这样就很好了。感谢大佬更新
