### ISSUE TITLE
info->dlpi_name指向了一个野指针

### ISSUE THREAD

**Issue by Mr-JingShi** [hexhacking/xDL#3]
### xDL Version

1.1.3

### Android OS Version

9.0

### Android ABIs

armeabi-v7a

### Device Manufacturers and Models

Google Pixel 3

### Describe the Bug

https://github.com/hexhacking/xDL/blob/3865f1d158d06fb71351b30843dfda85e0155aa5/xdl/src/main/cpp/xdl_iterate.c#L147

老师你好，
buf在作用域结束时变成了野指针，callback继续操作info->dlpi_name的话非常危险。
解决方案：在堆上malloc一段空间存放pathname；在callback结束后进行free

**Comment by caikelun** [comment]
谢谢你的关注和反馈。

在 `xdl_iterate_by_linker_cb` 执行 `return cb(info, size, cb_arg);` 时，会为 `cb` 调用开辟新的栈空间，`buf` 的内存空间在 `xdl_iterate_by_linker_cb` 的栈空间中，此时仍然是有效的，只有当 `xdl_iterate_by_linker_cb` 返回后它的栈空间才会被复用，因此在 `cb` 函数中读取 `buf` 中的内容是安全的，不会存在野指针的问题。可以结合汇编分析一下栈空间的状态。

这是一个比较常用的技巧，目的是为了避免额外的临时性堆内存申请和释放。

**Comment by Mr-JingShi** [comment]
明白了，之前我以为buf的内存空间在if ('/' != info->dlpi_name[0] && '[' != info->dlpi_name[0] && (0 != (flags & XDL_FULL_PATHNAME)))语句结束后就会被复用，仔细想了想，栈空间是所属于函数的而不是语句快，buf的栈空间是在 xdl_iterate_by_linker_cb函数内，所以cb(info, size, cb_arg)被调用时buff还是有效的，buf的作用域是在if语句块内，作用域和占空间被我搞混了。
谢谢老师
