### ISSUE TITLE
Static library

### ISSUE THREAD

**Issue by nick-botticelli** [hexhacking/xDL#6]
### the Feature, Motivation and Pitch

If it is possible, could a static version of the library be shipped in addition to the shared version? I am not sure about the limitations of Prefab, but I hope that it can be done. This would be very helpful for building it into my own native library without the need for 2+ shared libraries (and can potentially cause conflicts, etc.).

### Alternatives

Currently I manually download and modify the repo to build a static version to implement into my own native library.

**Comment by caikelun** [comment]
Hi @nick-botticelli,

Compilation and static linking are complex and closely related things. Modern compilers provide many parameters to control the size and execution performance of the product. Some parameters are related between compilation and static linking, such as LTO and outliner.

In addition, taking NDK with LLVM as an example, different NDK versions have different restrictions and bugs on the cooperation between compilation parameters and static link parameters.

So we can't assume in advance how your static linking method and parameters are configured.

It is recommended that you can integrate the xDL source code into your own project. We will not provide static libraries.

**Comment by nick-botticelli** [comment]
> Hi @nick-botticelli,
> 
> Compilation and static linking are complex and closely related things. Modern compilers provide many parameters to control the size and execution performance of the product. Some parameters are related between compilation and static linking, such as LTO and outliner.
> 
> In addition, taking NDK with LLVM as an example, different NDK versions have different restrictions and bugs on the cooperation between compilation parameters and static link parameters.
> 
> So we can't assume in advance how your static linking method and parameters are configured.
> 
> It is recommended that you can integrate the xDL source code into your own project. We will not provide static libraries.

Okay. Thank you for your response.
