### ISSUE TITLE
请问 xdl_sym 与 xdl_dsym 的实现是不是反了

### ISSUE THREAD

**Issue by zkwlx** [hexhacking/xDL#7]
### xDL Version

1.1.4

### Android OS Version

 不限版本

### Android ABIs

armeabi-v7a, arm64-v8a, x86, x86_64

### Device Manufacturers and Models

不限设备

### Describe the Bug

xdl_sym 内部实现是读取 .dynsym，xdl_dsym 内部实现是读取 .symtab，会不会是搞反了，还是有什么特殊含义？

**Comment by caikelun** [comment]
没有搞反。这里的 `d` 是 debugging 的意思，可以看下 readme：

`xdl_sym()` lookup "dynamic link symbols" in `.dynsym` as `dlsym()` does.

`xdl_dsym()` lookup "debuging symbols" in `.symtab` and "`.symtab` in `.gnu_debugdata`".

**Comment by zkwlx** [comment]
明白了，谢谢
